import Link from "next/link";
import { Plus, Search, Users } from "@/components/icons";
import { createClient } from "@/lib/supabase/server";
import { createCustomer } from "@/app/actions/customers";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { DataTable } from "@/components/ui/data-table";
import { Badge } from "@/components/ui/badge";
import { Field, SelectField } from "@/components/ui/form-field";
import { EmptyState } from "@/components/ui/empty-state";
import { formatDate } from "@/lib/utils";

export default async function CustomersPage({searchParams}:{searchParams:Promise<{q?:string;error?:string}>}){const p=await searchParams;const s=await createClient();let q=s.from('customers').select('id,display_name,customer_type,lifecycle,email,phone_e164,city,call_attempts,last_contact_at,customer_statuses(label,color)').is('deleted_at',null).order('created_at',{ascending:false}).limit(100);if(p.q)q=q.ilike('display_name',`%${p.q}%`);const {data}=await q;return <><PageHeader title="Kunder" description="Gemensam kärna för kontaktuppgifter, samtal, avtal, aktiviteter och historik." /><div className="split-layout"><Card><CardHeader><form className="toolbar-left"><div className="global-search" style={{width:340}}><Search size={16}/><input name="q" defaultValue={p.q} placeholder="Sök namn, företag eller nummer"/></div><button className="button button-secondary button-sm">Sök</button></form><Badge>{data?.length??0} poster</Badge></CardHeader><CardContent style={{padding:0}}>{data?.length?<DataTable headers={['Kund','Typ','Status','Kontakt','Ort','Försök','Senast kontakt']}>{data.map(c=>{const status=Array.isArray(c.customer_statuses)?c.customer_statuses[0]:c.customer_statuses;return <tr key={c.id}><td><Link href={`/app/customers/${c.id}`}><strong>{c.display_name}</strong></Link></td><td>{c.customer_type==='company'?'Företag':'Privatperson'}</td><td><Badge>{status?.label??c.lifecycle}</Badge></td><td>{c.phone_e164??c.email??'—'}</td><td>{c.city??'—'}</td><td>{c.call_attempts}</td><td>{formatDate(c.last_contact_at)}</td></tr>})}</DataTable>:<EmptyState icon={Users} title="Inga kunder ännu" description="Skapa den första kunden eller importera en lista."/>}</CardContent></Card><Card><CardHeader><h2><Plus size={16}/> Ny kund</h2></CardHeader><CardContent>{p.error?<p className="form-error">{p.error}</p>:null}<form action={createCustomer} className="form-stack"><SelectField label="Kundtyp" name="customer_type" defaultValue="company"><option value="company">Företag</option><option value="person">Privatperson</option></SelectField><Field label="Namn / företagsnamn" name="display_name" required/><Field label="Telefon" name="phone" placeholder="070-123 45 67"/><Field label="E-post" name="email" type="email"/><Field label="Ort" name="city"/><SelectField label="Livscykel" name="lifecycle" defaultValue="prospect"><option value="prospect">Prospekt</option><option value="lead">Lead</option><option value="customer">Kund</option></SelectField><button className="button button-primary"><Plus size={16}/> Skapa kund</button></form></CardContent></Card></div></>}
