import { NextResponse } from "next/server";
import { z } from "zod";
import { getAppContext } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { normalizePhone } from "@/lib/domain/phone";
import { randomToken, sha256 } from "@/lib/crypto";
import { serverEnv } from "@/lib/env";
import { assertPermission } from "@/lib/permissions";
export async function POST(request:Request){try{const ctx=await getAppContext();assertPermission(ctx.role,"calls.create");const parsed=z.object({customerId:z.uuid()}).parse(await request.json());const s=await createClient();const [{data:customer},{data:number},{data:voiceClient},{count:blocks}]=await Promise.all([s.from('customers').select('id,phone_e164,do_not_call').eq('id',parsed.customerId).single(),s.from('phone_numbers').select('id,number_e164').eq('supports_voice',true).eq('status','active').limit(1).maybeSingle(),s.from('voice_clients').select('client_number_e164').eq('assigned_user_id',ctx.userId).eq('status','active').maybeSingle(),s.from('compliance_blocks').select('*',{count:'exact',head:true}).eq('customer_id',parsed.customerId).eq('active',true).contains('channels',['call'])]);if(!customer?.phone_e164||!number||!voiceClient)return NextResponse.json({error:'telephony_not_configured'},{status:409});if(customer.do_not_call||blocks)return NextResponse.json({error:'customer_blocked'},{status:409});const to=normalizePhone(customer.phone_e164);const callbackToken=randomToken();const env=serverEnv();const {data:call,error}=await s.from('calls').insert({tenant_id:ctx.tenantId,customer_id:customer.id,phone_number_id:number.id,user_id:ctx.userId,direction:'outbound',from_number:number.number_e164,to_number:to,status:'queued',callback_token_hash:sha256(callbackToken+env.KUNDEXA_WEBHOOK_PEPPER),metadata:{mode:'webrtc_bridge'}}).select('id').single();if(error)return NextResponse.json({error:error.message},{status:400});await s.from('outbox_jobs').insert({tenant_id:ctx.tenantId,job_type:'call.start',aggregate_type:'call',aggregate_id:call.id,payload:{call_id:call.id,callback_token:callbackToken,voice_client_number:voiceClient.client_number_e164},idempotency_key:`call.start:${call.id}`});await s.from('activities').insert({tenant_id:ctx.tenantId,customer_id:customer.id,type:'call',status:'in_progress',title:'WebRTC-samtal',assigned_user_id:ctx.userId,created_by:ctx.userId,metadata:{call_id:call.id}});return NextResponse.json({callId:call.id,status:'queued'},{status:202})}catch(e){if(e instanceof z.ZodError)return NextResponse.json({error:'validation_error'},{status:422});return NextResponse.json({error:e instanceof Error?e.message:'internal_error'},{status:500})}}
