import { UserPlus, Users } from "@/components/icons";
import { createClient } from "@/lib/supabase/server";
import { inviteUser } from "@/app/actions/admin";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { DataTable } from "@/components/ui/data-table";
import { Field, SelectField } from "@/components/ui/form-field";
import { Badge } from "@/components/ui/badge";
import { formatDate } from "@/lib/utils";
export default async function UsersPage({searchParams}:{searchParams:Promise<{error?:string}>}){const p=await searchParams;const s=await createClient();const {data}=await s.from('tenant_memberships').select('user_id,role,status,joined_at,profiles:user_id(full_name,last_seen_at)').order('created_at');return <><PageHeader title="Användare" description="Roller för ägare, admin, teamledare, säljare, avtal, kvalitet, backoffice och ekonomi."/>{p.error?<p className="form-error">{p.error}</p>:null}<div className="split-layout"><Card><CardHeader><h2><Users size={17}/> Medlemmar</h2><Badge>{data?.length??0}</Badge></CardHeader><CardContent style={{padding:0}}><DataTable headers={['Namn','Roll','Status','Ansluten','Senast aktiv']}>{data?.map(m=>{const profile=Array.isArray(m.profiles)?m.profiles[0]:m.profiles;return <tr key={m.user_id}><td><strong>{profile?.full_name??'Inbjuden användare'}</strong></td><td>{m.role}</td><td><Badge className={m.status==='active'?'badge-success':'badge-warning'}>{m.status}</Badge></td><td>{formatDate(m.joined_at)}</td><td>{formatDate(profile?.last_seen_at)}</td></tr>})}</DataTable></CardContent></Card><Card><CardHeader><h2><UserPlus size={16}/> Bjud in</h2></CardHeader><CardContent><form action={inviteUser} className="form-stack"><Field label="E-post" name="email" type="email" required/><SelectField label="Roll" name="role"><option value="admin">Administratör</option><option value="team_lead">Teamledare</option><option value="sales">Säljare</option><option value="contract_manager">Avtalsansvarig</option><option value="quality">Kvalitetskontroll</option><option value="backoffice">Backoffice</option><option value="finance">Ekonomi</option><option value="viewer">Läsbehörig</option></SelectField><button className="button button-primary"><UserPlus size={16}/> Skicka inbjudan</button></form></CardContent></Card></div></>}
