import { Package, Plus } from "@/components/icons";
import { createClient } from "@/lib/supabase/server";
import { createProduct } from "@/app/actions/products";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { DataTable } from "@/components/ui/data-table";
import { Field, SelectField, TextareaField } from "@/components/ui/form-field";
import { Badge } from "@/components/ui/badge";
import { formatCurrency } from "@/lib/utils";
export default async function ProductsPage({searchParams}:{searchParams:Promise<{error?:string}>}){const p=await searchParams;const s=await createClient();const {data}=await s.from('products').select('id,name,sku,product_type,active,product_price_versions(setup_fee,recurring_fee,binding_months,notice_months,version)').order('created_at',{ascending:false});return <><PageHeader title="Produkter och priser" description="Versionshanterad produktkatalog som låses in i varje avtalsversion."/><div className="split-layout"><Card><CardHeader><h2>Produkter</h2><Badge>{data?.length??0}</Badge></CardHeader><CardContent style={{padding:0}}><DataTable headers={['Produkt','SKU','Typ','Startavgift','Månadspris','Bindning','Status']}>{data?.map(x=>{const prices=Array.isArray(x.product_price_versions)?x.product_price_versions:[];const price=prices.sort((a,b)=>b.version-a.version)[0];return <tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.sku??'—'}</td><td>{x.product_type}</td><td>{formatCurrency(Number(price?.setup_fee))}</td><td>{formatCurrency(Number(price?.recurring_fee))}</td><td>{price?.binding_months?`${price.binding_months} mån`:'—'}</td><td><Badge className={x.active?'badge-success':''}>{x.active?'Aktiv':'Inaktiv'}</Badge></td></tr>})}</DataTable></CardContent></Card><Card><CardHeader><h2><Plus size={16}/> Ny produkt</h2></CardHeader><CardContent>{p.error?<p className="form-error">{p.error}</p>:null}<form action={createProduct} className="form-stack"><Field label="Namn" name="name" required/><Field label="SKU" name="sku"/><SelectField label="Typ" name="product_type"><option value="service">Tjänst</option><option value="product">Produkt</option><option value="package">Paket</option></SelectField><TextareaField label="Beskrivning" name="description"/><div className="form-grid"><Field label="Startavgift" name="setup_fee" type="number" step="0.01" defaultValue="0"/><Field label="Månadsavgift" name="recurring_fee" type="number" step="0.01" defaultValue="0"/><Field label="Bindningstid (mån)" name="binding_months" type="number"/><Field label="Uppsägningstid (mån)" name="notice_months" type="number"/></div><button className="button button-primary"><Package size={16}/> Skapa produkt och prisversion</button></form></CardContent></Card></div></>}
