import Link from "next/link";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { DataTable } from "@/components/ui/data-table";
import { Field, SelectField, TextareaField } from "@/components/ui/form-field";
import { Search, ListFilter, RefreshCw, Megaphone } from "@/components/icons";
import { getAppContext } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { directorySearchSchema, searchDirectoryForTenant } from "@/lib/directory";
import { formatCurrency, formatDate } from "@/lib/utils";
import { createDirectorySegment, refreshDirectorySegment, sendSegmentToCampaign } from "@/app/actions/directory";

type Params = Record<string, string | string[] | undefined>;
const one = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
const num = (value: string | undefined) => value ? Number(value) : undefined;
const bool = (value: string | undefined) => value === undefined ? undefined : value === "true";
function inputFromParams(p: Params) {
  return directorySearchSchema.parse({
    entityType: one(p.entityType) || "organization", query: one(p.query), countryCode: one(p.countryCode) || "SE", county: one(p.county), municipality: one(p.municipality), city: one(p.city), postalCode: one(p.postalCode),
    sniCode: one(p.sniCode), legalForm: one(p.legalForm), organizationStatus: one(p.organizationStatus), employeeMin: num(one(p.employeeMin)), employeeMax: num(one(p.employeeMax)), revenueMin: num(one(p.revenueMin)), revenueMax: num(one(p.revenueMax)),
    resultMin: num(one(p.resultMin)), resultMax: num(one(p.resultMax)), hasPhone: bool(one(p.hasPhone)), hasEmail: bool(one(p.hasEmail)), hasWebsite: bool(one(p.hasWebsite)), phoneType: one(p.phoneType) || undefined,
    freshOnly: one(p.freshOnly) === "on", dataAgeDaysMax: num(one(p.dataAgeDaysMax)), latitude: num(one(p.latitude)), longitude: num(one(p.longitude)), radiusKm: num(one(p.radiusKm)),
    previouslyContacted: bool(one(p.previouslyContacted)), callAttemptsMin: num(one(p.callAttemptsMin)), customerLifecycle: one(p.customerLifecycle) || undefined, sort: one(p.sort) || "quality_desc", limit: 50, offset: num(one(p.offset)) ?? 0,
  });
}

export default async function DirectoryPage({ searchParams }: { searchParams: Promise<Params> }) {
  const p = await searchParams; const context = await getAppContext(); const input = inputFromParams(p); const shouldSearch = one(p.run) === "1";
  const result = shouldSearch ? await searchDirectoryForTenant(context.tenantId, input) : null; const supabase = await createClient();
  const [{ data: segments }, { data: campaigns }] = await Promise.all([
    supabase.from("segments").select("id,name,segment_type,last_refreshed_at,segment_snapshots(member_count,generated_at)").eq("tenant_id", context.tenantId).order("created_at", { ascending: false }).limit(30),
    supabase.from("campaigns").select("id,name,status").eq("tenant_id", context.tenantId).in("status", ["draft", "scheduled", "active"]).order("created_at", { ascending: false }),
  ]);
  return <>
    <PageHeader title="Katalog & målgrupper" description="Sök lokalt i Kundexas licensstyrda masterdata. Filter skapar aldrig premiumanrop; berikning och discovery körs separat." />
    {one(p.error) ? <p className="form-error">{one(p.error)}</p> : null}{one(p.message) ? <div className="notice success">{one(p.message)}</div> : null}
    <Card><CardHeader><h2><Search size={17}/> Lokal katalogsökning</h2><Badge>Ingen extern kostnad</Badge></CardHeader><CardContent>
      <form className="form-stack" method="get"><input type="hidden" name="run" value="1" />
        <div className="grid grid-4"><SelectField label="Entitet" name="entityType" defaultValue={input.entityType}><option value="organization">Företag</option><option value="establishment">Arbetsställe</option><option value="person">Privatperson</option></SelectField><Field label="Namn / org.nr" name="query" defaultValue={input.query ?? ""}/><Field label="Kommun" name="municipality" defaultValue={input.municipality ?? ""}/><Field label="Ort" name="city" defaultValue={input.city ?? ""}/><Field label="Län" name="county" defaultValue={input.county ?? ""}/><Field label="Postnummer" name="postalCode" defaultValue={input.postalCode ?? ""}/><Field label="SNI" name="sniCode" defaultValue={input.sniCode ?? ""}/><Field label="Juridisk form" name="legalForm" defaultValue={input.legalForm ?? ""}/><Field label="Min anställda" name="employeeMin" type="number" min="0" defaultValue={input.employeeMin ?? ""}/><Field label="Max anställda" name="employeeMax" type="number" min="0" defaultValue={input.employeeMax ?? ""}/><Field label="Min omsättning" name="revenueMin" type="number" defaultValue={input.revenueMin ?? ""}/><Field label="Max omsättning" name="revenueMax" type="number" defaultValue={input.revenueMax ?? ""}/><Field label="Latitud" name="latitude" type="number" step="any" defaultValue={input.latitude ?? ""}/><Field label="Longitud" name="longitude" type="number" step="any" defaultValue={input.longitude ?? ""}/><Field label="Radie km" name="radiusKm" type="number" min="0.1" step="any" defaultValue={input.radiusKm ?? ""}/><Field label="Max dataålder, dagar" name="dataAgeDaysMax" type="number" min="0" defaultValue={input.dataAgeDaysMax ?? ""}/></div>
        <div className="grid grid-4"><SelectField label="Telefon" name="hasPhone" defaultValue={input.hasPhone == null ? "" : String(input.hasPhone)}><option value="">Alla</option><option value="true">Har telefon</option><option value="false">Saknar telefon</option></SelectField><SelectField label="E-post" name="hasEmail" defaultValue={input.hasEmail == null ? "" : String(input.hasEmail)}><option value="">Alla</option><option value="true">Har e-post</option><option value="false">Saknar e-post</option></SelectField><SelectField label="Tidigare kontakt" name="previouslyContacted" defaultValue={input.previouslyContacted == null ? "" : String(input.previouslyContacted)}><option value="">Alla</option><option value="true">Kontaktad</option><option value="false">Inte kontaktad</option></SelectField><SelectField label="Sortering" name="sort" defaultValue={input.sort}><option value="quality_desc">Datakvalitet</option><option value="updated_desc">Senast uppdaterad</option><option value="name_asc">Namn A–Ö</option><option value="name_desc">Namn Ö–A</option></SelectField></div>
        <label><input type="checkbox" name="freshOnly" defaultChecked={input.freshOnly}/> Endast färska poster</label><button className="button button-primary"><Search size={16}/> Sök lokalt</button>
      </form>
    </CardContent></Card>
    {result ? <><div className="grid grid-4" style={{marginTop:18}}><Card><CardContent><strong>{result.summary.total}</strong><div className="muted">Totalt matchande</div></CardContent></Card><Card><CardContent><strong>{result.summary.fresh}</strong><div className="muted">Färska</div></CardContent></Card><Card><CardContent><strong>{result.summary.stale}</strong><div className="muted">Gamla</div></CardContent></Card><Card><CardContent><strong>{result.summary.missingPhone}</strong><div className="muted">Saknar telefon</div></CardContent></Card></div>
      <Card><CardHeader><h2>Resultat</h2><Badge>{result.data.length} visade av {result.summary.total}</Badge></CardHeader><CardContent style={{padding:0}}><DataTable headers={["Företag/person","Geografi","Bransch","Kontakt","Ekonomi","Freshness","Kvalitet"]}>{result.data.map(row=><tr key={row.id}><td><Link href={`/app/directory/${row.id}`}><strong>{row.canonical_name??"Licensierad katalogpost"}</strong></Link><div className="muted">{row.organization_number ?? row.entity_type}</div></td><td>{[row.postal_code,row.city,row.municipality,row.county].filter(Boolean).join(", ")||"—"}</td><td>{row.sni_code ?? "—"}<div className="muted">{row.industry ?? ""}</div></td><td>{row.phone_e164 ?? "—"}<div className="muted">{row.email ?? ""}</div></td><td>{row.revenue!=null?formatCurrency(row.revenue):"—"}<div className="muted">{row.employee_count??"—"} anställda</div></td><td><Badge className={row.freshness_state==="fresh"?"badge-success":row.freshness_state==="quarantined"?"badge-danger":""}>{row.freshness_state}</Badge><div className="muted">{formatDate(row.enriched_at)}</div></td><td>{Math.round(Number(row.data_quality_score??0))}/100</td></tr>)}</DataTable></CardContent></Card>
      <Card><CardHeader><h2><ListFilter size={16}/> Spara målgrupp</h2></CardHeader><CardContent><form action={createDirectorySegment} className="form-stack"><Field label="Segmentnamn" name="name" required/><TextareaField label="Beskrivning" name="description"/><SelectField label="Typ" name="segmentType" defaultValue="dynamic"><option value="dynamic">Dynamisk</option><option value="snapshot">Låst snapshot</option></SelectField>{Object.entries(input).map(([key,value])=>value==null||value===""||key==="limit"||key==="offset"?null:<input key={key} type="hidden" name={key} value={String(value)}/>)}<button className="button button-primary">Skapa segment av filtret</button></form></CardContent></Card></> : null}
    <Card><CardHeader><h2>Dynamiska segment</h2><Badge>{segments?.length??0}</Badge></CardHeader><CardContent style={{padding:0}}><DataTable headers={["Segment","Typ","Medlemmar","Senast uppdaterat","Åtgärder"]}>{segments?.map(segment=>{const snaps=Array.isArray(segment.segment_snapshots)?segment.segment_snapshots:[];const latest=[...snaps].sort((a,b)=>String(b.generated_at).localeCompare(String(a.generated_at)))[0];return <tr key={segment.id}><td><strong>{segment.name}</strong></td><td>{segment.segment_type}</td><td>{latest?.member_count??0}</td><td>{formatDate(segment.last_refreshed_at)}</td><td><div className="toolbar-left"><form action={refreshDirectorySegment}><input type="hidden" name="segment_id" value={segment.id}/><button className="button button-secondary button-sm"><RefreshCw size={14}/> Uppdatera</button></form>{campaigns?.length?<form action={sendSegmentToCampaign} className="toolbar-left"><input type="hidden" name="segment_id" value={segment.id}/><select name="campaign_id" required><option value="">Välj kampanj</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="button button-secondary button-sm"><Megaphone size={14}/> Skicka</button></form>:null}</div></td></tr>})}</DataTable></CardContent></Card>
  </>;
}
