import { Import, Upload } from "@/components/icons";
import { createClient } from "@/lib/supabase/server";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { DataTable } from "@/components/ui/data-table";
import { Badge } from "@/components/ui/badge";
import { formatDate } from "@/lib/utils";
import { processImport, rollbackImport } from "@/app/actions/imports";
export default async function ImportsPage({searchParams}:{searchParams:Promise<{error?:string;message?:string}>}){const p=await searchParams;const s=await createClient();const {data}=await s.from('import_runs').select('*').order('created_at',{ascending:false}).limit(100);return <><PageHeader title="Importer" description="CSV-import med simulering, normalisering, dubblettkontroll och återställningsunderlag."/>{p.error?<p className="form-error">{p.error}</p>:null}{p.message?<p className="notice">{p.message}</p>:null}<div className="split-layout"><Card><CardHeader><h2><Import size={17}/> Importkörningar</h2><Badge>{data?.length??0}</Badge></CardHeader><CardContent style={{padding:0}}><DataTable headers={['Import','Källa','Status','Rader','Nya','Dubletter','Spärrade','Fel','Datum','Åtgärd']}>{data?.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.source_type}</td><td><Badge className={x.status==='completed'?'badge-success':'badge-info'}>{x.status}</Badge></td><td>{x.total_rows}</td><td>{x.new_count}</td><td>{x.duplicate_count}</td><td>{x.blocked_count}</td><td>{x.error_count}</td><td>{formatDate(x.created_at)}</td><td>{x.status==='preview_ready'?<form action={processImport}><input type="hidden" name="import_run_id" value={x.id}/><button className="button button-primary button-sm">Genomför</button></form>:x.status==='completed'?<form action={rollbackImport}><input type="hidden" name="import_run_id" value={x.id}/><button className="button button-secondary button-sm">Återställ</button></form>:'—'}</td></tr>)}</DataTable></CardContent></Card><Card><CardHeader><h2><Upload size={17}/> Ladda upp CSV</h2></CardHeader><CardContent><form action="/api/v1/imports/csv" method="post" encType="multipart/form-data" className="form-stack"><label className="field"><span>Importnamn</span><input name="name" required/></label><label className="field"><span>CSV-fil</span><input type="file" name="file" accept="text/csv,.csv" required/></label><label style={{display:'flex',gap:9,fontSize:13}}><input type="checkbox" name="simulate" defaultChecked/> Simulera först utan att skapa kunder</label><button className="button button-primary"><Upload size={16}/> Validera import</button></form><div className="notice warning" style={{marginTop:16}}>Stödda kolumner: display_name, customer_type, email, phone, organization_number, city, county, industry, sni_code.</div></CardContent></Card></div></>}
