import { Megaphone, Plus } from "@/components/icons";
import { createClient } from "@/lib/supabase/server";
import { createCampaign } from "@/app/actions/campaigns";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { DataTable } from "@/components/ui/data-table";
import { Field, TextareaField } from "@/components/ui/form-field";
import { Badge } from "@/components/ui/badge";
import { formatDate } from "@/lib/utils";
export default async function CampaignsPage({searchParams}:{searchParams:Promise<{error?:string}>}){const p=await searchParams;const s=await createClient();const {data}=await s.from('campaigns').select('*,campaign_members(count)').order('created_at',{ascending:false});return <><PageHeader title="Kampanjer" description="Ringregler, försökstak, listor, team, manus och automationer per kampanj."/><div className="split-layout"><Card><CardHeader><h2>Alla kampanjer</h2><Badge>{data?.length??0}</Badge></CardHeader><CardContent style={{padding:0}}><DataTable headers={['Kampanj','Status','Ringtid','Max försök','Start','Budget']}>{data?.map(c=><tr key={c.id}><td><strong>{c.name}</strong><br/><span className="muted">{c.description??'—'}</span></td><td><Badge className={c.status==='active'?'badge-success':''}>{c.status}</Badge></td><td>{String(c.allowed_start_time).slice(0,5)}–{String(c.allowed_end_time).slice(0,5)}</td><td>{c.max_attempts}</td><td>{formatDate(c.starts_at)}</td><td>{c.budget??'—'}</td></tr>)}</DataTable></CardContent></Card><Card><CardHeader><h2><Plus size={16}/> Ny kampanj</h2></CardHeader><CardContent>{p.error?<p className="form-error">{p.error}</p>:null}<form action={createCampaign} className="form-stack"><Field label="Kampanjnamn" name="name" required/><TextareaField label="Beskrivning" name="description"/><div className="form-grid"><Field label="Ring från" name="start_time" type="time" defaultValue="09:00"/><Field label="Ring till" name="end_time" type="time" defaultValue="18:00"/><Field label="Max ringförsök" name="max_attempts" type="number" defaultValue="7" min="1" max="30"/></div><button className="button button-primary"><Megaphone size={16}/> Skapa kampanj</button></form></CardContent></Card></div></>}
