import { Headphones, PhoneCall } from "@/components/icons";
import { createClient } from "@/lib/supabase/server";
import { setCallDisposition } from "@/app/actions/communications";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { DataTable } from "@/components/ui/data-table";
import { Badge } from "@/components/ui/badge";
import { Field, SelectField } from "@/components/ui/form-field";
import { formatDate } from "@/lib/utils";
export default async function CallsPage(){const s=await createClient();const {data}=await s.from('calls').select('*,customers(display_name)').order('created_at',{ascending:false}).limit(100);return <><PageHeader title="Mina samtal" description="Samtalshistorik, resultat, anteckningar och återuppringningar."/><Card><CardHeader><h2><Headphones size={17}/> Samtal</h2><Badge>{data?.length??0}</Badge></CardHeader><CardContent style={{padding:0}}><DataTable headers={['Kund / nummer','Riktning','Status','Resultat','Tid','Efterarbete']}>{data?.map(call=>{const c=Array.isArray(call.customers)?call.customers[0]:call.customers;return <tr key={call.id}><td><strong>{c?.display_name??call.to_number}</strong><br/><span className="muted">{call.from_number} → {call.to_number}</span></td><td>{call.direction}</td><td><Badge className={call.status==='completed'?'badge-success':'badge-info'}>{call.status}</Badge></td><td>{call.disposition??'—'}</td><td>{formatDate(call.created_at)}</td><td>{call.disposition?'Klart':<form action={setCallDisposition} className="toolbar-left"><input type="hidden" name="call_id" value={call.id}/><select name="disposition" aria-label="Samtalsresultat" required><option value="">Resultat</option><option value="no_answer">Inget svar</option><option value="busy">Upptaget</option><option value="callback">Ring senare</option><option value="interested">Intresserad</option><option value="contract">Avtal ska skickas</option><option value="not_interested">Inte intresserad</option><option value="do_not_call">Ring ej igen</option></select><Field label="" name="notes" placeholder="Anteckning"/><button className="button button-primary button-sm">Spara</button></form>}</td></tr>})}</DataTable></CardContent></Card></>}
