import { Mail, Send } from "@/components/icons";
import { createClient } from "@/lib/supabase/server";
import { queueEmail } from "@/app/actions/communications";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Field, SelectField, TextareaField } from "@/components/ui/form-field";
import { Badge } from "@/components/ui/badge";
import { formatDate } from "@/lib/utils";
export default async function EmailPage({searchParams}:{searchParams:Promise<{customer?:string;error?:string}>}){const p=await searchParams;const s=await createClient();const [{data:customers},{data:messages}]=await Promise.all([s.from('customers').select('id,display_name,email,do_not_email').not('email','is',null).order('display_name'),s.from('email_messages').select('*,customers(display_name)').order('created_at',{ascending:false}).limit(60)]);return <><PageHeader title="E-post" description="Transaktionella utskick med tenantens verifierade domän, mallar och leveranshändelser."/>{p.error?<p className="form-error">{p.error}</p>:null}<div className="split-layout"><Card><CardHeader><h2>Utskick</h2><Badge>{messages?.length??0}</Badge></CardHeader><CardContent>{messages?.map(m=>{const c=Array.isArray(m.customers)?m.customers[0]:m.customers;return <div className="activity-line" key={m.id}><span className="activity-dot"><Mail size={14}/></span><div><strong>{m.subject}</strong><p>{c?.display_name??m.to_addresses.join(', ')}</p><small className="muted">{m.status}</small></div><time>{formatDate(m.created_at)}</time></div>})}</CardContent></Card><Card><CardHeader><h2><Send size={16}/> Nytt e-postmeddelande</h2></CardHeader><CardContent><form action={queueEmail} className="form-stack"><SelectField label="Kund" name="customer_id" defaultValue={p.customer??''} required><option value="">Välj kund</option>{customers?.map(c=><option key={c.id} value={c.id} disabled={c.do_not_email}>{c.display_name} · {c.email}{c.do_not_email?' · SPÄRRAD':''}</option>)}</SelectField><Field label="Ämne" name="subject" required/><TextareaField label="Meddelande" name="body" required/><button className="button button-primary"><Send size={16}/> Lägg i sändkö</button></form></CardContent></Card></div></>}
