import Link from "next/link";
import { FileSignature, Plus } from "@/components/icons";
import { createClient } from "@/lib/supabase/server";
import { createContract } from "@/app/actions/contracts";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { DataTable } from "@/components/ui/data-table";
import { Field, SelectField } from "@/components/ui/form-field";
import { Badge } from "@/components/ui/badge";
import { formatCurrency, formatDate } from "@/lib/utils";
export default async function ContractsPage({searchParams}:{searchParams:Promise<{error?:string;customer?:string}>}){const p=await searchParams;const s=await createClient();const [{data:contracts},{data:customers},{data:products}]=await Promise.all([s.from('contracts').select('id,contract_number,title,status,audience,value,currency,created_at,customers(display_name)').order('created_at',{ascending:false}).limit(100),s.from('customers').select('id,display_name').is('deleted_at',null).order('display_name'),s.from('products').select('id,name').eq('active',true).order('name')]);return <><PageHeader title="Avtal" description="Skapa, versionslås, skicka, följ och bevisa varje avtal."/><div className="split-layout"><Card><CardHeader><h2>Avtalsregister</h2><Badge>{contracts?.length??0}</Badge></CardHeader><CardContent style={{padding:0}}><DataTable headers={['Avtal','Kund','Typ','Status','Värde','Skapat']}>{contracts?.map(c=>{const customer=Array.isArray(c.customers)?c.customers[0]:c.customers;return <tr key={c.id}><td><Link href={`/app/contracts/${c.id}`}><strong>{c.contract_number}</strong><br/><span className="muted">{c.title}</span></Link></td><td>{customer?.display_name??'—'}</td><td>{c.audience}</td><td><Badge className={['signed','active'].includes(c.status)?'badge-success':c.status==='draft'?'':'badge-info'}>{c.status}</Badge></td><td>{formatCurrency(Number(c.value),c.currency)}</td><td>{formatDate(c.created_at)}</td></tr>})}</DataTable></CardContent></Card><Card><CardHeader><h2><Plus size={16}/> Skapa avtal</h2></CardHeader><CardContent>{p.error?<p className="form-error">{p.error}</p>:null}<form action={createContract} className="form-stack"><SelectField label="Kund" name="customer_id" defaultValue={p.customer??''} required><option value="">Välj kund</option>{customers?.map(c=><option value={c.id} key={c.id}>{c.display_name}</option>)}</SelectField><SelectField label="Produkt" name="product_id"><option value="">Utan produkt</option>{products?.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</SelectField><Field label="Avtalstitel" name="title" placeholder="Företagsabonnemang" required/><SelectField label="Försäljningskanal" name="sales_channel" defaultValue="telephone"><option value="telephone">Telefonförsäljning</option><option value="web">Webb</option><option value="email">E-post</option><option value="in_person">Fysiskt möte</option><option value="partner">Partner</option><option value="other">Övrigt</option></SelectField><button className="button button-primary"><FileSignature size={16}/> Skapa låsbar version</button></form></CardContent></Card></div></>}
