import Link from "next/link";
import { ArrowLeft, Download, FileSignature, LockKeyhole, Phone, Send, Upload } from "@/components/icons";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { activateContract, cancelFutureContractReminders, extendContractExpiry, linkContractSourceCall, registerExternalContractCall, sendContract, sendContractReminder, uploadContractPdf } from "@/app/actions/contracts";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Field, SelectField, TextareaField } from "@/components/ui/form-field";
import { formatCurrency, formatDate } from "@/lib/utils";

const labels: Record<string, string> = { draft: "Utkast", ready: "Redo", sent: "Skickat", delivered: "Levererat", opened: "Öppnat", accepted: "Accepterat", declined: "Avstått", expired: "Utgånget", superseded: "Ersatt", cancelled: "Avbrutet", signed: "Dokumenterat", active: "Aktivt", queued: "Köad", submitting: "Skickas", failed: "Misslyckad", bounced: "Studsad", complained: "Rapporterad", suppressed: "Undertryckt", clicked: "Länk klickad", delayed: "Fördröjd", dead_letter: "Kräver åtgärd", pending: "Väntar" };
const localDateTime = (value?: string | null) => value ? new Date(new Date(value).getTime() - new Date(value).getTimezoneOffset() * 60_000).toISOString().slice(0, 16) : "";

export default async function ContractDetail({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; message?: string }> }) {
  const { id } = await params;
  const query = await searchParams;
  const supabase = await createClient();
  const [{ data: contract }, { data: versions }, { data: documents }, { data: deliveries }, { data: events }, { data: acceptances }, { data: requests }, { data: reminders }, { data: evidence }] = await Promise.all([
    supabase.from("contracts").select("*,customers(display_name,email,phone_e164),products(name),tenant_legal_entities(legal_name,organization_number)").eq("id", id).single(),
    supabase.from("contract_versions").select("*").eq("contract_id", id).order("version", { ascending: false }),
    supabase.from("contract_documents").select("*").eq("contract_id", id).order("created_at", { ascending: false }),
    supabase.from("contract_deliveries").select("*,contract_recipients(full_name,email,phone_e164)").eq("contract_id", id).order("created_at", { ascending: false }),
    supabase.from("contract_events").select("*").eq("contract_id", id).order("occurred_at", { ascending: false }),
    supabase.from("contract_acceptances").select("*").eq("contract_id", id).order("created_at", { ascending: false }),
    supabase.from("contract_acceptance_requests").select("*").eq("contract_id", id).order("created_at", { ascending: false }),
    supabase.from("contract_reminders").select("*").eq("contract_id", id).order("scheduled_at", { ascending: true }),
    supabase.from("evidence_packages").select("*").eq("contract_id", id).order("created_at", { ascending: false }),
  ]);
  if (!contract) notFound();
  const customer = Array.isArray(contract.customers) ? contract.customers[0] : contract.customers;
  const product = Array.isArray(contract.products) ? contract.products[0] : contract.products;
  const legalEntity = Array.isArray(contract.tenant_legal_entities) ? contract.tenant_legal_entities[0] : contract.tenant_legal_entities;
  const activeRequest = requests?.find((request) => request.status === "pending") ?? null;
  const { data: sourceCall } = contract.source_call_id ? await supabase.from("calls").select("id,started_at,answered_at,ended_at,duration_seconds,direction,disposition,notes,user_id,metadata").eq("id", contract.source_call_id).maybeSingle() : { data: null };
  const { data: eligibleRaw } = await supabase.rpc("resolve_contract_eligible_calls", { p_customer_id: contract.customer_id });
  const eligibleCalls = (eligibleRaw ?? []) as Array<{ id: string; ended_at: string; disposition: string; duration_seconds: number; registered_manually: boolean }>;
  const { data: dispositions } = await supabase.from("list_dispositions").select("key,label").eq("contract_eligible", true).order("sort_order");
  const latestDelivery = deliveries?.[0] ?? null;
  const canonicalDocument = documents?.find((document) => ["generated_pdf", "source_pdf"].includes(document.document_type) && (document.metadata as Record<string, unknown> | null)?.canonical === true) ?? null;
  const accepted = acceptances?.[0] ?? null;
  const reminderSentCount = reminders?.filter((reminder) => reminder.status === "sent").length ?? 0;
  const now = new Date();
  const start = new Date(now.getTime() - 5 * 60_000);

  return <>
    <Link href="/app/contracts" className="muted" style={{ display: "inline-flex", gap: 6, alignItems: "center", marginBottom: 16 }}><ArrowLeft size={15} /> Till avtal</Link>
    <PageHeader title={`${contract.contract_number} · ${contract.title}`} description={`${customer?.display_name ?? "Okänd kund"} · ${product?.name ?? "Fristående avtal"}`} action={<Badge className={["accepted", "signed", "active"].includes(contract.status) ? "badge-success" : "badge-info"}>{labels[contract.status] ?? contract.status}</Badge>} />
    {query.error ? <p className="form-error">{query.error}</p> : null}{query.message ? <p className="notice">{query.message}</p> : null}
    {!contract.source_call_id ? <div className="notice warning"><strong>Utskick blockerat:</strong> avtalet saknar ett giltigt tidigare kundsamtal. Utkastet kan granskas och kompletteras, men versionen låses inte förrän samtalet är länkat.</div> : null}
    {latestDelivery && ["failed", "bounced", "complained", "suppressed", "dead_letter"].includes(latestDelivery.status) ? <div className="notice warning"><strong>Leveransfel:</strong> {latestDelivery.failure_message ?? labels[latestDelivery.status] ?? latestDelivery.status}. Automatiska e-postpåminnelser stoppas vid permanent bounce, complaint eller suppression.</div> : null}

    <div className="split-layout" style={{ marginTop: 16 }}>
      <div className="grid">
        <Card><CardHeader><h2>Avtal</h2><LockKeyhole size={18} /></CardHeader><CardContent><dl className="key-value"><dt>Status</dt><dd>{labels[contract.status] ?? contract.status}</dd><dt>Juridiskt bolag</dt><dd>{legalEntity?.legal_name ?? "—"}{legalEntity?.organization_number ? ` · ${legalEntity.organization_number}` : ""}</dd><dt>Kund</dt><dd>{customer?.display_name ?? "—"}</dd><dt>Produkt</dt><dd>{product?.name ?? "—"}</dd><dt>Värde</dt><dd>{formatCurrency(Number(contract.value), contract.currency)}</dd><dt>Start</dt><dd>{formatDate(contract.starts_on)}</dd><dt>Slut</dt><dd>{formatDate(contract.ends_on)}</dd><dt>Bindningstid</dt><dd>{contract.binding_months ? `${contract.binding_months} månader` : "—"}</dd><dt>Uppsägningstid</dt><dd>{contract.notice_months ? `${contract.notice_months} månader` : "—"}</dd><dt>Sista svarsdatum</dt><dd>{formatDate(contract.expires_at)}</dd><dt>Skapat</dt><dd>{formatDate(contract.created_at)}</dd></dl></CardContent></Card>
        {versions?.map((version) => <Card key={version.id}><CardHeader><h2>Version {version.version}</h2><Badge className={version.locked_at ? "badge-success" : ""}>{version.locked_at ? "Låst" : "Redigerbar"}</Badge></CardHeader><CardContent><h3>{version.title}</h3><p style={{ lineHeight: 1.7, whiteSpace: "pre-wrap" }}>{version.rendered_body}</p>{version.rendered_terms ? <><h4>Villkor</h4><p style={{ lineHeight: 1.7, whiteSpace: "pre-wrap" }}>{version.rendered_terms}</p></> : null}<div className="notice"><strong>Snapshot SHA-256</strong><br /><code>{version.snapshot_hash ?? version.document_hash}</code></div></CardContent></Card>)}
        <Card><CardHeader><h2>Dokument</h2><Badge>{documents?.length ?? 0}</Badge></CardHeader><CardContent>{documents?.length ? documents.map((document) => <div className="activity-line" key={document.id}><span className="activity-dot"><FileSignature size={14} /></span><div><strong>{document.file_name}</strong><p>{document.document_type} · {(document.metadata as Record<string, unknown> | null)?.canonical === true ? "kanoniskt · " : ""}SHA {document.sha256.slice(0, 16)}…</p></div><Link className="button button-ghost" href={`/api/v1/contracts/${id}/documents/${document.id}`}><Download size={14} /> Hämta</Link></div>) : <p className="muted">Kanonisk PDF genereras vid utskick eller kan väljas från uppladdad PDF.</p>}</CardContent></Card>
        <Card><CardHeader><h2>Händelser</h2><Badge>{events?.length ?? 0}</Badge></CardHeader><CardContent>{events?.map((event) => <div className="activity-line" key={event.id}><span className="activity-dot"><FileSignature size={14} /></span><div><strong>{labels[event.event_type] ?? event.event_type}</strong></div><time>{formatDate(event.occurred_at)}</time></div>)}</CardContent></Card>
      </div>

      <div className="grid">
        <Card><CardHeader><h3><Phone size={16} /> Källsamtal</h3>{sourceCall ? <Badge className="badge-success">Kopplat</Badge> : <Badge className="badge-warning">Saknas</Badge>}</CardHeader><CardContent>{sourceCall ? <dl className="key-value"><dt>Avslutat</dt><dd>{formatDate(sourceCall.ended_at)}</dd><dt>Riktning</dt><dd>{sourceCall.direction}</dd><dt>Disposition</dt><dd>{sourceCall.disposition}</dd><dt>Duration</dt><dd>{sourceCall.duration_seconds ?? 0} sekunder</dd><dt>Typ</dt><dd>{(sourceCall.metadata as Record<string, unknown> | null)?.registered_manually === true ? "Externt, manuellt registrerat" : "Kundexa-samtal"}</dd><dt>Anteckning</dt><dd>{sourceCall.notes ?? "—"}</dd></dl> : <>
          {eligibleCalls.length ? <form action={linkContractSourceCall} className="form-stack"><input type="hidden" name="contract_id" value={id} /><SelectField label="Giltigt tidigare samtal" name="source_call_id" required><option value="">Välj samtal</option>{eligibleCalls.map((call) => <option key={call.id} value={call.id}>{formatDate(call.ended_at)} · {call.disposition} · {call.duration_seconds}s{call.registered_manually ? " · manuellt" : ""}</option>)}</SelectField><button className="button button-secondary">Länka samtal</button></form> : <p className="muted">Inget avtalsgrundande samtal hittades.</p>}
          <details style={{ marginTop: 14 }}><summary><strong>Registrera tidigare samtal</strong></summary><form action={registerExternalContractCall} className="form-stack" style={{ marginTop: 12 }}><input type="hidden" name="contract_id" value={id} /><input type="hidden" name="customer_id" value={contract.customer_id} /><Field label="Telefonnummer" name="phone_e164" defaultValue={customer?.phone_e164 ?? ""} required /><SelectField label="Riktning" name="direction"><option value="outbound">Utgående</option><option value="inbound">Inkommande</option></SelectField><Field label="Start" name="started_at" type="datetime-local" defaultValue={localDateTime(start.toISOString())} required /><Field label="Slut" name="ended_at" type="datetime-local" defaultValue={localDateTime(now.toISOString())} required /><SelectField label="Disposition" name="disposition" required><option value="">Välj</option>{dispositions?.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</SelectField><TextareaField label="Anteckning" name="note" required /><Field label="Extern referens" name="external_reference" /><label><input type="checkbox" name="confirmed" required /> Jag bekräftar att samtalet genomfördes.</label><button className="button button-secondary">Registrera och länka</button></form></details>
        </>}</CardContent></Card>

        <Card><CardHeader><h3><Send size={16} /> Granska och skicka</h3></CardHeader><CardContent><p className="muted">Slutlig bekräftelse låser aktiv version, binder exakt PDF och skapar en personlig acceptlänk.</p><form action={sendContract} className="form-stack"><input type="hidden" name="contract_id" value={id} /><Field label="Mottagarens namn" name="recipient_name" defaultValue={customer?.display_name ?? ""} required /><Field label="Mottagarens e-post" name="recipient_email" type="email" defaultValue={customer?.email ?? ""} /><SelectField label="Kanal" name="channel" defaultValue="both"><option value="both">E-post och SMS</option><option value="email">E-post</option><option value="sms">SMS</option></SelectField><TextareaField label="Personlig introduktion" name="introduction" placeholder="Tack för samtalet. Här kommer avtalet vi gick igenom." /><Field label="Sista svarsdatum" name="expires_at" type="datetime-local" defaultValue={localDateTime(contract.expires_at ?? new Date(Date.now() + 7 * 86400000).toISOString())} required /><Field label="Reply-to (valfri)" name="reply_to" type="email" /><div className="notice warning"><strong>Detta låser avtalsversionen och skickar den till kunden.</strong><br />Källsamtal: {sourceCall ? `${formatDate(sourceCall.ended_at)} · ${sourceCall.disposition}` : "saknas"}<br />PDF: {canonicalDocument?.file_name ?? "genereras automatiskt vid bekräftelse"}</div><button className="button button-primary" disabled={!sourceCall || !["ready", "sent", "delivered", "opened"].includes(contract.status)}><Send size={16} /> Lås och skicka</button></form></CardContent></Card>

        <Card><CardHeader><h3><Upload size={16} /> Ladda upp PDF</h3></CardHeader><CardContent><form action={uploadContractPdf} className="form-stack"><input type="hidden" name="contract_id" value={id} /><label className="field"><span>PDF-fil, högst 20 MB</span><input type="file" name="file" accept="application/pdf" required /></label><SelectField label="Användning" name="document_mode" defaultValue="attachment"><option value="attachment">Använd endast som bilaga</option><option value="canonical">Använd som kanoniskt avtalsdokument</option></SelectField><button className="button button-secondary"><Upload size={16} /> Kontrollera hash och ladda upp</button></form></CardContent></Card>

        <Card><CardHeader><h3>Utskick</h3><Badge>{deliveries?.length ?? 0}</Badge></CardHeader><CardContent>{deliveries?.map((delivery) => { const recipient = Array.isArray(delivery.contract_recipients) ? delivery.contract_recipients[0] : delivery.contract_recipients; return <div className="activity-line" key={delivery.id}><span className="activity-dot"><Send size={14} /></span><div><strong>{recipient?.full_name ?? "Mottagare"}</strong><p>{delivery.delivery_kind} · {delivery.channel} · {labels[delivery.status] ?? delivery.status}{delivery.provider_status ? ` · ${delivery.provider_status}` : ""}</p>{delivery.failure_message ? <p className="form-error">{delivery.failure_message}</p> : null}</div><time>{formatDate(delivery.sent_at ?? delivery.created_at)}</time></div>; })}</CardContent></Card>

        <Card><CardHeader><h3>Påminnelser</h3><Badge>{reminderSentCount} skickade</Badge></CardHeader><CardContent>{reminders?.map((reminder) => <div className="activity-line" key={reminder.id}><span className="activity-dot"><Send size={14} /></span><div><strong>{reminder.kind === "automatic" ? `Automatisk ${reminder.sequence_number}` : "Manuell"}</strong><p>{reminder.channel} · {labels[reminder.status] ?? reminder.status}</p></div><time>{formatDate(reminder.sent_at ?? reminder.scheduled_at)}</time></div>)}{activeRequest ? <><form action={sendContractReminder} className="form-stack" style={{ marginTop: 14 }}><input type="hidden" name="contract_id" value={id} /><input type="hidden" name="idempotency_key" value={crypto.randomUUID()} /><SelectField label="Kanal" name="channel"><option value="email">E-post</option><option value="sms">SMS</option><option value="both">Båda</option></SelectField><TextareaField label="Personligt meddelande" name="personal_message" /><label><input type="checkbox" name="attach_pdf" defaultChecked /> Bifoga kanonisk PDF i e-post</label><button className="button button-secondary">Skicka påminnelse</button></form><form action={cancelFutureContractReminders} style={{ marginTop: 10 }}><input type="hidden" name="contract_id" value={id} /><button className="button button-ghost">Avbryt framtida påminnelser</button></form></> : <p className="muted">Ingen aktiv acceptbegäran.</p>}</CardContent></Card>

        {activeRequest ? <Card><CardHeader><h3>Acceptans</h3><Badge>{labels[activeRequest.status] ?? activeRequest.status}</Badge></CardHeader><CardContent><dl className="key-value"><dt>Skapad</dt><dd>{formatDate(activeRequest.created_at)}</dd><dt>Öppnad</dt><dd>{formatDate(activeRequest.opened_at)}</dd><dt>Giltig till</dt><dd>{formatDate(activeRequest.expires_at)}</dd><dt>Dokumenthash</dt><dd><code>{activeRequest.canonical_document_sha256?.slice(0, 24)}…</code></dd></dl><form action={extendContractExpiry} className="form-stack"><input type="hidden" name="contract_id" value={id} /><Field label="Förläng sista svarsdatum" name="expires_at" type="datetime-local" defaultValue={localDateTime(activeRequest.expires_at)} required /><button className="button button-secondary">Förläng med audit</button></form></CardContent></Card> : null}
        {accepted ? <Card><CardHeader><h3><LockKeyhole size={16} /> Dokumenterad acceptans</h3><Badge className="badge-success">{labels[accepted.status] ?? accepted.status}</Badge></CardHeader><CardContent><dl className="key-value"><dt>Tidpunkt</dt><dd>{formatDate(accepted.accepted_at)}</dd><dt>Metod</dt><dd>{accepted.method}</dd><dt>Namn/fras</dt><dd>{accepted.acceptance_phrase ?? accepted.normalized_response ?? "—"}</dd><dt>IP</dt><dd>{accepted.ip_address == null ? "—" : String(accepted.ip_address)}</dd><dt>Dokumenthash</dt><dd><code>{accepted.canonical_document_sha256?.slice(0, 24)}…</code></dd></dl><p>Bevispaket: {evidence?.[0]?.status ?? "väntar"}</p>{contract.status === "accepted" ? <form action={activateContract}><input type="hidden" name="contract_id" value={id} /><button className="button button-primary"><LockKeyhole size={16} /> Aktivera efter beviskontroll</button></form> : null}</CardContent></Card> : null}
      </div>
    </div>
  </>;
}
