"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { getAppContext } from "@/lib/auth";
import { normalizePhone } from "@/lib/domain/phone";
import { assertPermission } from "@/lib/permissions";

const value=(fd:FormData,key:string)=>String(fd.get(key)??"").trim();
export async function createCustomer(fd:FormData){const ctx=await getAppContext(); assertPermission(ctx.role,"customers.write"); const schema=z.object({type:z.enum(["person","company"]),displayName:z.string().min(2),email:z.union([z.email(),z.literal("")]),phone:z.string().optional(),city:z.string().optional(),lifecycle:z.enum(["prospect","lead","customer"])}); const parsed=schema.safeParse({type:value(fd,"customer_type"),displayName:value(fd,"display_name"),email:value(fd,"email"),phone:value(fd,"phone"),city:value(fd,"city"),lifecycle:value(fd,"lifecycle")}); if(!parsed.success) redirect('/app/customers?error=Kontrollera kunduppgifterna'); let phone:string|null=null; if(parsed.data.phone){try{phone=normalizePhone(parsed.data.phone)}catch{redirect('/app/customers?error=Ogiltigt telefonnummer')}} const supabase=await createClient(); const {data:status}=await supabase.from('customer_statuses').select('id').eq('key','new').single(); const {data,error}=await supabase.from('customers').insert({tenant_id:ctx.tenantId,customer_type:parsed.data.type,display_name:parsed.data.displayName,email:parsed.data.email||null,phone_e164:phone,city:parsed.data.city||null,lifecycle:parsed.data.lifecycle,status_id:status?.id,created_by:ctx.userId,assigned_user_id:ctx.userId}).select('id').single(); if(error) redirect(`/app/customers?error=${encodeURIComponent(error.message)}`); await supabase.from('audit_logs').insert({tenant_id:ctx.tenantId,actor_user_id:ctx.userId,action:'customer.created',entity_type:'customer',entity_id:data.id,after_data:{display_name:parsed.data.displayName}}); revalidatePath('/app/customers'); redirect(`/app/customers/${data.id}`)}
export async function addNote(fd:FormData){const ctx=await getAppContext(); assertPermission(ctx.role,"customers.write"); const customerId=value(fd,'customer_id'); const body=value(fd,'body'); if(!body)return; const supabase=await createClient(); await supabase.from('notes').insert({tenant_id:ctx.tenantId,customer_id:customerId,body,created_by:ctx.userId}); revalidatePath(`/app/customers/${customerId}`)}
export async function addActivity(fd:FormData){const ctx=await getAppContext();assertPermission(ctx.role,"customers.write");const customerId=value(fd,'customer_id');const title=value(fd,'title');const due=value(fd,'due_at');if(!title)return;const supabase=await createClient();await supabase.from('activities').insert({tenant_id:ctx.tenantId,customer_id:customerId,type:'task',title,assigned_user_id:ctx.userId,due_at:due||null,created_by:ctx.userId});revalidatePath(`/app/customers/${customerId}`)}
export async function blockCustomer(fd:FormData){const ctx=await getAppContext();assertPermission(ctx.role,"customers.write");const customerId=value(fd,'customer_id');const reason=value(fd,'reason')||'Kundens invändning';const supabase=await createClient();await supabase.from('customers').update({do_not_call:true,do_not_sms:true,do_not_email:true,lifecycle:'blocked',blocked_reason:reason}).eq('id',customerId);await supabase.from('compliance_blocks').insert({tenant_id:ctx.tenantId,customer_id:customerId,channels:['call','sms','email'],reason,created_by:ctx.userId});await supabase.from('audit_logs').insert({tenant_id:ctx.tenantId,actor_user_id:ctx.userId,action:'customer.blocked',entity_type:'customer',entity_id:customerId,after_data:{reason}});revalidatePath(`/app/customers/${customerId}`)}
