"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { getAppContext } from "@/lib/auth";
import { normalizePhone } from "@/lib/domain/phone";
import { zonedLocalDateTimeToIso } from "@/lib/domain/time";
import { assertPermission } from "@/lib/permissions";

const value=(fd:FormData,key:string)=>String(fd.get(key)??"").trim();
export async function createCustomer(fd:FormData){const ctx=await getAppContext(); assertPermission(ctx.role,"customers.write"); const schema=z.object({type:z.enum(["person","company"]),displayName:z.string().min(2),email:z.union([z.email(),z.literal("")]),phone:z.string().optional(),city:z.string().optional(),lifecycle:z.enum(["prospect","lead","customer"])}); const parsed=schema.safeParse({type:value(fd,"customer_type"),displayName:value(fd,"display_name"),email:value(fd,"email"),phone:value(fd,"phone"),city:value(fd,"city"),lifecycle:value(fd,"lifecycle")}); if(!parsed.success) redirect('/app/customers?error=Kontrollera kunduppgifterna'); let phone:string|null=null; if(parsed.data.phone){try{phone=normalizePhone(parsed.data.phone)}catch{redirect('/app/customers?error=Ogiltigt telefonnummer')}} const supabase=await createClient(); const {data:status}=await supabase.from('customer_statuses').select('id').eq('key','new').single(); const {data,error}=await supabase.from('customers').insert({tenant_id:ctx.tenantId,customer_type:parsed.data.type,display_name:parsed.data.displayName,email:parsed.data.email||null,phone_e164:phone,city:parsed.data.city||null,lifecycle:parsed.data.lifecycle,status_id:status?.id,created_by:ctx.userId,assigned_user_id:ctx.userId}).select('id').single(); if(error) redirect(`/app/customers?error=${encodeURIComponent(error.message)}`); await supabase.from('audit_logs').insert({tenant_id:ctx.tenantId,actor_user_id:ctx.userId,action:'customer.created',entity_type:'customer',entity_id:data.id,after_data:{display_name:parsed.data.displayName}}); revalidatePath('/app/customers'); redirect(`/app/customers/${data.id}`)}
export async function addNote(fd:FormData){const ctx=await getAppContext(); assertPermission(ctx.role,"customers.write"); const customerId=value(fd,'customer_id'); const body=value(fd,'body'); if(!body)return; const visibility=value(fd,'visibility')||'team'; const noteType=value(fd,'note_type')||'general'; const supabase=await createClient(); const {error}=await supabase.from('notes').insert({tenant_id:ctx.tenantId,customer_id:customerId,body,visibility,note_type:noteType,is_pinned:fd.get('is_pinned')==='on',created_by:ctx.userId}); if(error)redirect(`/app/customers/${customerId}?error=${encodeURIComponent(error.message)}`); revalidatePath(`/app/customers/${customerId}`)}
export async function updateNote(fd:FormData){const ctx=await getAppContext();assertPermission(ctx.role,"customers.write");const customerId=value(fd,"customer_id");const noteId=value(fd,"note_id");const body=value(fd,"body");if(!body)redirect(`/app/customers/${customerId}?error=Anteckningen får inte vara tom`);const supabase=await createClient();const {error}=await supabase.from("notes").update({body,visibility:value(fd,"visibility")||"team",is_pinned:fd.get("is_pinned")==="on"}).eq("id",noteId).eq("customer_id",customerId);if(error)redirect(`/app/customers/${customerId}?error=${encodeURIComponent(error.message)}`);revalidatePath(`/app/customers/${customerId}`);redirect(`/app/customers/${customerId}?note=updated`)}
export async function archiveNote(fd:FormData){const ctx=await getAppContext();assertPermission(ctx.role,"customers.write");const customerId=value(fd,"customer_id");const noteId=value(fd,"note_id");const supabase=await createClient();const {error}=await supabase.from("notes").update({archived_at:new Date().toISOString()}).eq("id",noteId).eq("customer_id",customerId);if(error)redirect(`/app/customers/${customerId}?error=${encodeURIComponent(error.message)}`);revalidatePath(`/app/customers/${customerId}`);redirect(`/app/customers/${customerId}?note=archived`)}
export async function addActivity(fd:FormData){const ctx=await getAppContext();assertPermission(ctx.role,"customers.write");const customerId=value(fd,'customer_id');const title=value(fd,'title');const due=value(fd,'due_at');if(!title)return;const supabase=await createClient();await supabase.from('activities').insert({tenant_id:ctx.tenantId,customer_id:customerId,type:'task',title,assigned_user_id:ctx.userId,due_at:due||null,created_by:ctx.userId});revalidatePath(`/app/customers/${customerId}`)}
export async function blockCustomer(fd:FormData){const ctx=await getAppContext();assertPermission(ctx.role,"customers.write");const customerId=value(fd,'customer_id');const reason=value(fd,'reason')||'Kundens invändning';const supabase=await createClient();await supabase.from('customers').update({do_not_call:true,do_not_sms:true,do_not_email:true,lifecycle:'blocked',blocked_reason:reason}).eq('id',customerId);await supabase.from('compliance_blocks').insert({tenant_id:ctx.tenantId,customer_id:customerId,channels:['call','sms','email'],reason,created_by:ctx.userId});await supabase.from('audit_logs').insert({tenant_id:ctx.tenantId,actor_user_id:ctx.userId,action:'customer.blocked',entity_type:'customer',entity_id:customerId,after_data:{reason}});revalidatePath(`/app/customers/${customerId}`)}

export async function scheduleCallback(fd:FormData){const ctx=await getAppContext();assertPermission(ctx.role,"callbacks.create");const customerId=value(fd,'customer_id');const due=value(fd,'due_at');const scope=value(fd,'scope');if(!customerId||!due)redirect(`/app/customers/${customerId}?error=Tid för återkomst krävs`);let iso:string;try{iso=zonedLocalDateTimeToIso(due,ctx.tenantTimezone)}catch{redirect(`/app/customers/${customerId}?error=Ogiltig tid för tenantens tidszon`)}const supabase=await createClient();const {error}=await supabase.rpc('schedule_customer_callback',{p_customer_id:customerId,p_list_id:value(fd,'list_id')||null,p_scope:scope,p_due_at:iso,p_title:value(fd,'title')||'Återkomst',p_description:value(fd,'description')});if(error)redirect(`/app/customers/${customerId}?error=${encodeURIComponent(error.message)}`);revalidatePath(`/app/customers/${customerId}`);revalidatePath('/app/callbacks');redirect(`/app/customers/${customerId}?callback=created`)}

export async function createManualProspect(fd:FormData){const ctx=await getAppContext();assertPermission(ctx.role,"customers.write");let phone:string;try{phone=normalizePhone(value(fd,'phone'))}catch{redirect('/app/dialer?error=Ogiltigt telefonnummer')}const supabase=await createClient();const {data,error}=await supabase.rpc('create_or_match_manual_prospect',{p_display_name:value(fd,'display_name')||phone,p_phone_e164:phone,p_customer_type:value(fd,'customer_type')==='company'?'company':'person'});if(error)redirect(`/app/dialer?error=${encodeURIComponent(error.message)}`);const result=data as {customerId?:string};if(!result.customerId)redirect('/app/dialer?error=Prospektet kunde inte skapas');revalidatePath('/app/prospects');redirect(`/app/dialer?customer=${result.customerId}`)}
