import { Activity, FileSignature, PhoneCall, Target, TrendingUp, Users } from "@/components/icons";
import { createClient } from "@/lib/supabase/server";
import { PageHeader } from "@/components/ui/page-header";
import { StatCard } from "@/components/ui/stat-card";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { DataTable } from "@/components/ui/data-table";
import { Badge } from "@/components/ui/badge";
import { formatCurrency, formatDate } from "@/lib/utils";

export default async function DashboardPage(){const s=await createClient();const [customers,calls,contracts,deals,activities,recentContracts]=await Promise.all([s.from('customers').select('*',{count:'exact',head:true}).is('deleted_at',null),s.from('calls').select('*',{count:'exact',head:true}).gte('created_at',new Date(Date.now()-86400000).toISOString()),s.from('contracts').select('*',{count:'exact',head:true}).in('status',['sent','delivered','opened','signing']),s.from('deals').select('value,status'),s.from('activities').select('*',{count:'exact',head:true}).eq('status','open'),s.from('contracts').select('id,contract_number,title,status,value,currency,created_at,customers(display_name)').order('created_at',{ascending:false}).limit(6)]);const won=(deals.data??[]).filter(d=>d.status==='won').reduce((a,d)=>a+Number(d.value),0);return <><PageHeader title="Dashboard" description="Realtidsbild av försäljning, aktiviteter och avtal." /><div className="grid grid-4"><StatCard icon={Users} label="Kunder och prospekt" value={customers.count??0} detail="Aktiva poster"/><StatCard icon={PhoneCall} label="Samtal idag" value={calls.count??0} detail="In- och utgående"/><StatCard icon={FileSignature} label="Avtal väntar" value={contracts.count??0} detail="Skickade eller öppnade"/><StatCard icon={TrendingUp} label="Vunnet värde" value={formatCurrency(won)} detail="Alla vunna affärer"/></div><div className="grid grid-2" style={{marginTop:18}}><Card><CardHeader><h2>Senaste avtal</h2><Badge>{recentContracts.data?.length??0} st</Badge></CardHeader><CardContent style={{padding:0}}><DataTable headers={['Avtal','Kund','Status','Värde','Skapat']}>{(recentContracts.data??[]).map(c=>{const customer=Array.isArray(c.customers)?c.customers[0]:c.customers;return <tr key={c.id}><td><strong>{c.contract_number}</strong><br/><span className="muted">{c.title}</span></td><td>{customer?.display_name??'—'}</td><td><Badge className={c.status==='signed'?'badge-success':'badge-info'}>{c.status}</Badge></td><td>{formatCurrency(Number(c.value),c.currency)}</td><td>{formatDate(c.created_at)}</td></tr>})}</DataTable></CardContent></Card><Card><CardHeader><h2>Arbetsläge</h2><Target size={18}/></CardHeader><CardContent><div className="grid grid-2"><StatCard icon={Activity} label="Öppna aktiviteter" value={activities.count??0}/><StatCard icon={Target} label="Öppna affärer" value={(deals.data??[]).filter(d=>d.status==='open').length}/></div><div className="notice" style={{marginTop:16}}>Kundexa stoppar samtal, SMS och e-post innan utskick när kunden har en aktiv spärr eller invändning.</div></CardContent></Card></div></>}
